### ISSUE TITLE
现在表单的短链好像变了..

### ISSUE THREAD

**Issue by TioaTyan** [GDGNanyang/gdgdocs#10]
现在的表单短链地址变成了：
https://goo.gl/forms/************

直接替换的方法不行了

**Comment by chenglu** [comment]
抱歉最近忙，请仔细阅读一下文档先～

格式如 goo.gl/forms/xxx 的短链接目前无法使用这个，这个只是对前端资源的替代，我们无法修改/控制短链接跳转之后的长链接呢。
