### ISSUE TITLE
貌似Google对Forms的反代增加了人机验证

### ISSUE THREAD

**Issue by bzdk** [GDGNanyang/gdgdocs#13]
具体表现，就是在反代Google Forms的界面会尝试加载recaptcha的js，并要求人机验证。

**Comment by chenglu** [comment]
Yes, 已经替换相关资源，保证在国内可用了，如果你发现有任何问题，请再反馈。

另外，在后台的时候不勾选 “收集电子邮件地址”，就不会出现人机验证的选项。

Thanks!

**Comment by bzdk** [comment]
非常感谢。
