### ISSUE TITLE
请问gdgdocs的ditu api是否可以开源

### ISSUE THREAD

**Issue by unsir** [GDGNanyang/gdgdocs#14]
一直需要用google map api，实在不想用高德或者百度地图api替代。但是奈何国内用户访问的时候 会xxx。求问ditu.gdgdocs.org是否可以开源

**Comment by chenglu** [comment]
这些服务目前都没有精力维护了，所以无开源计划。

最近打算找/成立一个开源组织，接管这些用于开发技术研究的东西，同时看是否可以让他们提供一些商用/合作的解决方案。

谢谢！
