### ISSUE TITLE
Google 人机验证码毁所有

### ISSUE THREAD

**Issue by btccomgogo** [GDGNanyang/gdgdocs#17]
提交您的表单回复时出错，请完成人机识别系统的验证并重试。

**Comment by adamyi** [comment]
I think this was raised before in #13 ?

**Comment by adamyi** [comment]
As for your error, did you set-up your own server or use our service at gdgdocs.org? I don't think that reCAPTCHA is still a problem on gdgdocs.org, but it still is on self-hosted versions.

**Comment by chenglu** [comment]
确证 Google 人机验证码毁所有…

因为这是一个反向代理机制的服务，reCAPTCHA 无法完成后端验证，所以不要使用 Email 收集功能啊。
