### ISSUE TITLE
无法使用 Google Docs/Spreadsheet/Slide

### ISSUE THREAD

**Issue by miroccur** [GDGNanyang/gdgdocs#18]
当使用 www.gdgdocs.org 打开一个docs的时候，页面可以加载出来，但是内容无法同步，并且会转入离线模式。

**Comment by chenglu** [comment]
因为有人使用反代 docs 的一篇大学生公开声明文档被封锁，故主站已经关闭 Docs/Spreadsheet/Slide 访问。
