### ISSUE TITLE
很赞的项目！

### ISSUE THREAD

**Issue by tvvocold** [GDGNanyang/gdgdocs#7]
期待更多支持！
另外，CentOS7可以吗?

--
ps:http://www.gdgny.org/ 打开很困难。被墙了？

**Comment by chenglu** [comment]
我改天在centos7上实验一下，www.gdgny.org 中的一些Google资源未反代 有些是 gtatic.cn 的内容被干扰，这周末解决这些问题。

**Comment by tvvocold** [comment]
nice!

**Comment by chenglu** [comment]
@tvvocold 现在南阳GDG官网打开速度已快成狗，亲试试咯。另外Centos7 么有发现什么不兼容的，哈哈。

**Comment by tvvocold** [comment]
赞!

**Comment by tvvocold** [comment]
能否把Google Fonts 反代的实现也开源下?

**Comment by chenglu** [comment]
那就是一个配置文件而已，没必要开个repo开源了。

https://gist.github.com/chenglu/bcff977b28431e57c1a2
